### ISSUE TITLE
Dataset preprocessing and split

### ISSUE THREAD

**Issue by levayz** [iabh1shekbasu/LungCancerDetectionEnsemble#1]
Hi,

I wanted to ask what did you use to process the LIDC dataset and if you can make the script available?
Also, how did you choose to split the dataset to train/test/val? Did you split the scans first or did you split the dataset after getting all the nodule slices? Can you add to the published dataset a list of what scans ids belong to which split?

Thank you!

**Comment by iabh1shekbasu** [comment]
Hi,

We want to clarify that our team has not pre-processed the data used in this project. Instead, it has been sourced directly from an existing repository, which you can access via the following link:

https://github.com/swethasubramanian/LungCancerDetection

If you have any questions or need more information, please refer to the aforementioned repository.
