### ISSUE TITLE
Error when trying to train Inception V3

### ISSUE THREAD

**Issue by levayz** [iabh1shekbasu/LungCancerDetectionEnsemble#2]
Hi,

when running the cell for training the inception v3 i get the following error:
```
 28 model = train_model(model, criterion, optimizer, step_lr_scheduler, num_epochs=10, model_name = "inception_v3")

Cell In[20], line 24, in train_model(model, criterion, optimizer, scheduler, num_epochs, model_name)
     21 # forward
     22 # track history if only in train
     23 with torch.set_grad_enabled(phase == 'train'):
---> 24     outputs = model(inputs)
     25     _, preds = torch.max(outputs, 1) #was (outputs,1) for non-inception and (outputs.data,1) for inception
     26     loss = criterion(outputs, labels)

File D:\python310\medsamvenv\lib\site-packages\torch\nn\modules\module.py:1511, in Module._wrapped_call_impl(self, *args, **kwargs)
   1509     return self._compiled_call_impl(*args, **kwargs)  # type: ignore[misc]
   1510 else:
-> 1511     return self._call_impl(*args, **kwargs)

File D:\python310\medsamvenv\lib\site-packages\torch\nn\modules\module.py:1520, in Module._call_impl(self, *args, **kwargs)
   1515 # If we don't have any hooks, we want to skip the rest of the logic in
   1516 # this function, and just call forward.
   1517 if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
   1518         or _global_backward_pre_hooks or _global_backward_hooks
   1519         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1520     return forward_call(*args, **kwargs)
   1522 try:
   1523     result = None

File D:\python310\medsamvenv\lib\site-packages\torchvision\models\inception.py:166, in Inception3.forward(self, x)
    164 def forward(self, x: Tensor) -> InceptionOutputs:
    165     x = self._transform_input(x)
--> 166     x, aux = self._forward(x)
    167     aux_defined = self.training and self.aux_logits
    168     if torch.jit.is_scripting():

File D:\python310\medsamvenv\lib\site-packages\torchvision\models\inception.py:138, in Inception3._forward(self, x)
    136 if self.AuxLogits is not None:
    137     if self.training:
--> 138         aux = self.AuxLogits(x)
    139 # N x 768 x 17 x 17
    140 x = self.Mixed_7a(x)

File D:\python310\medsamvenv\lib\site-packages\torch\nn\modules\module.py:1511, in Module._wrapped_call_impl(self, *args, **kwargs)
   1509     return self._compiled_call_impl(*args, **kwargs)  # type: ignore[misc]
   1510 else:
-> 1511     return self._call_impl(*args, **kwargs)

File D:\python310\medsamvenv\lib\site-packages\torch\nn\modules\module.py:1520, in Module._call_impl(self, *args, **kwargs)
   1515 # If we don't have any hooks, we want to skip the rest of the logic in
   1516 # this function, and just call forward.
   1517 if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
   1518         or _global_backward_pre_hooks or _global_backward_hooks
   1519         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1520     return forward_call(*args, **kwargs)
   1522 try:
   1523     result = None

File D:\python310\medsamvenv\lib\site-packages\torchvision\models\inception.py:386, in InceptionAux.forward(self, x)
    384 x = self.conv0(x)
    385 # N x 128 x 5 x 5
--> 386 x = self.conv1(x)
    387 # N x 768 x 1 x 1
    388 # Adaptive average pooling
    389 x = F.adaptive_avg_pool2d(x, (1, 1))

File D:\python310\medsamvenv\lib\site-packages\torch\nn\modules\module.py:1511, in Module._wrapped_call_impl(self, *args, **kwargs)
   1509     return self._compiled_call_impl(*args, **kwargs)  # type: ignore[misc]
   1510 else:
-> 1511     return self._call_impl(*args, **kwargs)

File D:\python310\medsamvenv\lib\site-packages\torch\nn\modules\module.py:1520, in Module._call_impl(self, *args, **kwargs)
   1515 # If we don't have any hooks, we want to skip the rest of the logic in
   1516 # this function, and just call forward.
   1517 if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
   1518         or _global_backward_pre_hooks or _global_backward_hooks
   1519         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1520     return forward_call(*args, **kwargs)
   1522 try:
   1523     result = None

File D:\python310\medsamvenv\lib\site-packages\torchvision\models\inception.py:405, in BasicConv2d.forward(self, x)
    404 def forward(self, x: Tensor) -> Tensor:
--> 405     x = self.conv(x)
    406     x = self.bn(x)
    407     return F.relu(x, inplace=True)

File D:\python310\medsamvenv\lib\site-packages\torch\nn\modules\module.py:1511, in Module._wrapped_call_impl(self, *args, **kwargs)
   1509     return self._compiled_call_impl(*args, **kwargs)  # type: ignore[misc]
   1510 else:
-> 1511     return self._call_impl(*args, **kwargs)

File D:\python310\medsamvenv\lib\site-packages\torch\nn\modules\module.py:1520, in Module._call_impl(self, *args, **kwargs)
   1515 # If we don't have any hooks, we want to skip the rest of the logic in
   1516 # this function, and just call forward.
   1517 if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
   1518         or _global_backward_pre_hooks or _global_backward_hooks
   1519         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1520     return forward_call(*args, **kwargs)
   1522 try:
   1523     result = None

File D:\python310\medsamvenv\lib\site-packages\torch\nn\modules\conv.py:460, in Conv2d.forward(self, input)
    459 def forward(self, input: Tensor) -> Tensor:
--> 460     return self._conv_forward(input, self.weight, self.bias)

File D:\python310\medsamvenv\lib\site-packages\torch\nn\modules\conv.py:456, in Conv2d._conv_forward(self, input, weight, bias)
    452 if self.padding_mode != 'zeros':
    453     return F.conv2d(F.pad(input, self._reversed_padding_repeated_twice, mode=self.padding_mode),
    454                     weight, bias, self.stride,
    455                     _pair(0), self.dilation, self.groups)
--> 456 return F.conv2d(input, weight, bias, self.stride,
    457                 self.padding, self.dilation, self.groups)

RuntimeError: Calculated padded input size per channel: (4 x 4). Kernel size: (5 x 5). Kernel size can't be greater than actual input size
```

It seems like the AuxLogits are being ran even though you set it to False after instantiating the pretrained model.
I tried instantiating the model with `aux_logits=False` but it can't be done for the pretrained version.

Do you need to use the AuxLogits in your training function?
How do you suggest to proceed? 

Thanks,
Lev.

**Comment by kun2001github** [comment]
Hi ~ have you solved this problem? I also encountered the same problem

`RuntimeError                              Traceback (most recent call last)
Cell In[18], [line 26](vscode-notebook-cell:?execution_count=18&line=26)
     [17](vscode-notebook-cell:?execution_count=18&line=17) # StepLR Decays the learning rate of each parameter group by gamma every step_size epochs
     [18](vscode-notebook-cell:?execution_count=18&line=18) # Decay LR by a factor of 0.1 every 7 epochs
     [19](vscode-notebook-cell:?execution_count=18&line=19) # Learning rate scheduling should be applied after optimizer’s update
   (...)
     [23](vscode-notebook-cell:?execution_count=18&line=23) #     validate(...)
     [24](vscode-notebook-cell:?execution_count=18&line=24) #     scheduler.step()
     [25](vscode-notebook-cell:?execution_count=18&line=25) step_lr_scheduler = lr_scheduler.StepLR(optimizer, step_size = 10, gamma=0.1)
---> [26](vscode-notebook-cell:?execution_count=18&line=26) model = train_model(model, criterion, optimizer, step_lr_scheduler, num_epochs=10, model_name = "inception_v3")

Cell In[13], [line 23](vscode-notebook-cell:?execution_count=13&line=23)
     [20](vscode-notebook-cell:?execution_count=13&line=20) # forward
     [21](vscode-notebook-cell:?execution_count=13&line=21) # track history if only in train
     [22](vscode-notebook-cell:?execution_count=13&line=22) with torch.set_grad_enabled(phase == 'train'):
---> [23](vscode-notebook-cell:?execution_count=13&line=23)     outputs = model(inputs)
     [24](vscode-notebook-cell:?execution_count=13&line=24)     _, preds = torch.max(outputs, 1) #was (outputs,1) for non-inception and (outputs.data,1) for inception
     [25](vscode-notebook-cell:?execution_count=13&line=25)     loss = criterion(outputs, labels)

File /opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py:1501, in Module._call_impl(self, *args, **kwargs)
   [1496](https://vscode-remote+ssh-002dremote-002b127-002e0-002e0-002e1.vscode-resource.vscode-cdn.net/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py:1496) # If we don't have any hooks, we want to skip the rest of the logic in
   [1497](https://vscode-remote+ssh-002dremote-002b127-002e0-002e0-002e1.vscode-resource.vscode-cdn.net/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py:1497) # this function, and just call forward.
   [1498](https://vscode-remote+ssh-002dremote-002b127-002e0-002e0-002e1.vscode-resource.vscode-cdn.net/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py:1498) if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
   [1499](https://vscode-remote+ssh-002dremote-002b127-002e0-002e0-002e1.vscode-resource.vscode-cdn.net/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py:1499)         or _global_backward_pre_hooks or _global_backward_hooks
...
    [458](https://vscode-remote+ssh-002dremote-002b127-002e0-002e0-002e1.vscode-resource.vscode-cdn.net/opt/conda/lib/python3.10/site-packages/torch/nn/modules/conv.py:458)                     _pair(0), self.dilation, self.groups)
--> [459](https://vscode-remote+ssh-002dremote-002b127-002e0-002e0-002e1.vscode-resource.vscode-cdn.net/opt/conda/lib/python3.10/site-packages/torch/nn/modules/conv.py:459) return F.conv2d(input, weight, bias, self.stride,
    [460](https://vscode-remote+ssh-002dremote-002b127-002e0-002e0-002e1.vscode-resource.vscode-cdn.net/opt/conda/lib/python3.10/site-packages/torch/nn/modules/conv.py:460)                 self.padding, self.dilation, self.groups)

RuntimeError: Calculated padded input size per channel: (4 x 4). Kernel size: (5 x 5). Kernel size can't be greater than actual input size`

**Comment by levayz** [comment]
Hi, yes i have. Not sure if this is a good solution... it a bit hacky:

```
model = models.inception_v3(pretrained = True)
model.aux_logits = False
# Handle the auxilary net
num_ftrs = model.AuxLogits.fc.in_features
model.AuxLogits.fc = nn.Linear(num_ftrs, num_classes)
# Handle the primary net
num_ftrs = model.fc.in_features
model.fc = nn.Linear(num_ftrs,num_classes)
print("Number of features: "+str(num_ftrs))
#model.classifier = nn.Linear(num_ftrs, num_classes) ## for vgg19
model.fc = nn.Linear(num_ftrs, num_classes)  ##for googlenet, resnet18
#model.classifier = nn.Linear(num_ftrs, num_classes) ## for densenet169
model = model.to(device)
criterion = nn.CrossEntropyLoss( weight = torch.tensor([1, 4.7]).to(device))
# Observe that all parameters are being optimized
optimizer = optim.Adam(model.parameters(), lr=0.0001)
# StepLR Decays the learning rate of each parameter group by gamma every step_size epochs
# Decay LR by a factor of 0.1 every 7 epochs
# Learning rate scheduling should be applied after optimizer’s update
# e.g., you should write your code this way:
# for epoch in range(100):
#     train(...)
#     validate(...)
#     scheduler.step()
step_lr_scheduler = lr_scheduler.StepLR(optimizer, step_size = 10, gamma=0.1)
AuxLogits = model.AuxLogits
model.AuxLogits=None
model = train_model(model, criterion, optimizer, step_lr_scheduler, num_epochs=10, model_name = "inception_v3")
```

take a look at the 2 before last lines.
I set model.AuxLogits to None so that the models doesnt use it.
I do save the pretrained version of it but it doesnt look like the authors are using them.

**Comment by kun2001github** [comment]
Well, thank you very much for your help。
I've researched another way myself, but training，
Epoch only 5 iterations, it was over。

My modification was added during data preprocessing，transforms. CenterCrop(299)
The following code
``` 
data_transforms = {
    'train': transforms.Compose([
        transforms.Resize((256,256)),
        transforms.ToTensor(),
        transforms.Normalize(mean, std),
        transforms.CenterCrop(299),
    ]),
    'val': transforms.Compose([
        transforms.Resize((256,256)),
        transforms.ToTensor(),
        transforms.CenterCrop(299),
    ]),
    'test': transforms.Compose([
       transforms.Resize((256,256)),
        transforms.ToTensor(),
        transforms.CenterCrop(299),
    ]),
}
```

**Comment by iabh1shekbasu** [comment]
Hi, @levayz @kun2001github , Sorry I have been super busy lately, so I couldn't respond.

Regarding this issue, 

Cell In[20], line 24,

_, preds = torch.max(outputs, 1) 

For inception based models, you have to replace it with 

_, preds = (outputs.data, 1)

it was stated in the comment.

**Comment by levayz** [comment]
> Hi, @levayz @kun2001github , Sorry I have been super busy lately, so I couldn't respond.
> 
> Regarding this issue,
> 
> Cell In[20], line 24,
> 
> _, preds = torch.max(outputs, 1)
> 
> For inception based models, you have to replace it with
> 
> _, preds = (outputs.data, 1)
> 
> it was stated in the comment.

Thank you!
